2021-02-16 17:32:56,299 ERROR: Exception on / [GET] [in C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\application\routes.py", line 16, in home
    return render_template('home.html', title='Home page', recipes=recipes)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\application\templates\home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\application\templates\base.html", line 26, in top-level template code
    <a class="navbar-brand" href="{{ url_for('index') }}">RecipeShare</a>
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'login' instead?
2021-02-16 17:32:59,893 ERROR: Exception on / [GET] [in C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\application\routes.py", line 16, in home
    return render_template('home.html', title='Home page', recipes=recipes)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\application\templates\home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\application\templates\base.html", line 26, in top-level template code
    <a class="navbar-brand" href="{{ url_for('index') }}">RecipeShare</a>
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "C:\Users\Jake\PycharmProjects\RecipeSharingApp\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'login' instead?
2021-02-16 17:33:40,619 INFO: Microblog startup [in C:\Users\Jake\PycharmProjects\RecipeSharingApp\application\__init__.py:57]
2021-02-16 17:36:20,710 INFO: Microblog startup [in C:\Users\Jake\PycharmProjects\RecipeSharingApp\application\__init__.py:57]
2021-02-16 17:37:18,634 INFO: Microblog startup [in C:\Users\Jake\PycharmProjects\RecipeSharingApp\application\__init__.py:57]
2021-02-16 17:37:56,504 INFO: Microblog startup [in C:\Users\Jake\PycharmProjects\RecipeSharingApp\application\__init__.py:57]
